# mini-raft-kv 本地开发配置

server:
  host: "127.0.0.1"
  port: 8000
  v: 1

client:
  host: "127.0.0.1"
  port: 8000
  timeout: 5.0
  max_retries: 3
  v: 1

wal:
  path: "data/wal.log"
  sync_mode: always          # always | batch | timer
  batch_count: 10
  batch_interval_ms: 1000                # 1s 写一次

log:
  level: info                # debug | info | warn | error
  file: null                 # null = 只输出到控制台
  color: true

sst:
  path : "data/.tmp"

rc:
  mode : ""
